### ISSUE TITLE
Click on a file name + line open the file but not goto to the line 

### ISSUE THREAD

**Issue by Champal** [sokolovstas/SublimeWebInspector#105]
Hi, 

In the "Javascript Console" when I click on file.js:xxx, the good file.js is open but the "Goto Line" don't work.

SublimeText build 3083 
SublimeWebInspector 1.7.4

SublimeText Console :
```javascript
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "views in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 264, in run
  File "C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package\views.py", line 149, in check_click
  File "swi in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 1437, in open_script_by_id_and_focus_line
  File "swi in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 1444, in open_script_and_focus_line_by_filename
  File "swi in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 1431, in do_when
  File "swi in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 1444, in <lambda>
  File "swi in C:\Users\x\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 1447, in open_script_and_focus_line_callback
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by danmosemsft** [comment]
I created st3-1.7.5-prerelease. This is the only change. To try it:

To receive pre-release versions, instead of blessed versions, add Web Inspector to your install_prereleases section of your Package Control user settings, for example:
"install_prereleases":
[
"Web Inspector"
]

**Comment by danmosemsft** [comment]
Let me know if it works well for you and I can upgrade to a real release later.

**Comment by Champal** [comment]
Hi, with v1.7.5-prerelease it almost work. It's going to n+1 line !
