### ISSUE TITLE
Error trying to start SWI

### ISSUE THREAD

**Issue by lifzgreat** [sokolovstas/SublimeWebInspector#73]
Every time I try to run WebInspector, I get the following error message in ST3's console:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "swi in C:\Users\chris\AppData\Roaming\Sublime Text 3\Installed Packages\Web Inspector.sublime-package", line 253, in run
KeyError: 'windows_x64'
```

**Comment by danmosemsft** [comment]
That means that this line is missing from swi.sublime-settings. It is present currently, so perhaps your file was corrupt or mismatched.

		"windows_x64": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",

**Comment by lifzgreat** [comment]
Thanks, that fixed it!
