### ISSUE TITLE
Not starting on OSX Sublime Text 3

### ISSUE THREAD

**Issue by montogeek** [sokolovstas/SublimeWebInspector#94]
Log:
```
startup, version: 3083 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/montogeek/Library/Application Support/Sublime Text 3/Packages
state path: /Users/montogeek/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/montogeek/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage", "JavaScript Completions", "SublimeLinter-jshint"]
pre session restore time: 4.46534
first paint time: 4.5798
startup time: 4.61472
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin Color Highlighter.ColorHighlighter
reloading plugin Color Highlighter.colors
reloading plugin ColorSchemeSelector.ColorSchemeSelector
reloading plugin DashDoc.DashDoc
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_compare
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin JSCS-Formatter.JSCS-Formatter
reloading plugin Laravel 4 Facades.Facades
reloading plugin LESS.less_completions
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-jscs.linter
SublimeLinter: jscs linter loaded 
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin TrailingSpaces.trailing_spaces
reloading plugin Web Inspector.swi
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "swi in /Users/montogeek/Library/Application Support/Sublime Text 3/Installed Packages/Web Inspector.sublime-package", line 1
    ﻿import hashlib
            ^
SyntaxError: invalid character in identifier
reloading plugin Web Inspector.websocket
reloading plugin 42 Headers.42 Headers
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
reloading plugin tern_for_sublime.tern
reloading plugin WakaTime.WakaTime
plugins loaded
[WakaTime] Initializing WakaTime plugin v4.0.8
SublimeLinter: debug mode: off 
SublimeLinter: jscs activated: /Users/montogeek/.nvm/versions/v0.12.1/bin/jscs (disabled in settings) 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-07-09 20:18:15, next run at 2015-07-09 21:18:15 or after

```

**Comment by danmosemsft** [comment]
I will dig out my mac and see what I can find out.

**Comment by danmosemsft** [comment]
This is most likely because some of the files, including swi.py, got a BOM prepended, likely by Notepad. Although Python [claims](https://www.python.org/dev/peps/pep-0263/) to accept a BOM, it may be causing this to fail here on the first line.
When I built a plugin without the BOM's it began to work on my OSX box. Deployed and we'll see whether the official package is fixed as well.

**Comment by montogeek** [comment]
Thanks!

**Comment by danmosemsft** [comment]
Aw nuts. Downloaded the latest bits from package manager, it still reproduces.

**Comment by danmosemsft** [comment]
ah! I mistyped the release name st-1.6.1 instead of st3.1.6.1. Package manager ignored it...

**Comment by danmosemsft** [comment]
Confirmed it works now.

For my future reference, need to run something like this script before any commit, to fix any BOM that crept in.

#!/bin/sh
git diff --cached --diff-filter=ACMR --name-only -z *.py | xargs -0 -n 1 sh -c '
    for FILE; do
        sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE"
    done
' sh

**Comment by montogeek** [comment]
Thanks!
